name: koopon
description: A university marketplace app
# You can adjust the version as needed
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  path: ^1.9.1
  
  # Add other dependencies as needed
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add assets, fonts, etc. as needed
  assets:
    - images/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700