name: koopon
description: A university marketplace app
# You can adjust the version as needed
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # This is the line you need to add

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  # Add other Firebase products as needed