// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lSIfGwcWuwhXSgqHSKNc4Hp7kV6eO04',
    appId: '1:96137870116:web:b27d9d5833d3335a05d1b1',
    messagingSenderId: '96137870116',
    projectId: 'koopon-41d5a',
    authDomain: 'koopon-41d5a.firebaseapp.com',
    storageBucket: 'koopon-41d5a.firebasestorage.app',
    measurementId: 'G-FV08JX3CFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr2awZy1JQNURFuSHIrFiYtAcEGVeUF04',
    appId: '1:96137870116:android:6a3b71336b8b412a05d1b1',
    messagingSenderId: '96137870116',
    projectId: 'koopon-41d5a',
    storageBucket: 'koopon-41d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk03j0OWeH8yueCuB1mRD7I4VNlWPyL04',
    appId: '1:96137870116:ios:836ae2f0d5b8f8d905d1b1',
    messagingSenderId: '96137870116',
    projectId: 'koopon-41d5a',
    storageBucket: 'koopon-41d5a.firebasestorage.app',
    iosBundleId: 'com.example.koopon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk03j0OWeH8yueCuB1mRD7I4VNlWPyL04',
    appId: '1:96137870116:ios:836ae2f0d5b8f8d905d1b1',
    messagingSenderId: '96137870116',
    projectId: 'koopon-41d5a',
    storageBucket: 'koopon-41d5a.firebasestorage.app',
    iosBundleId: 'com.example.koopon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2lSIfGwcWuwhXSgqHSKNc4Hp7kV6eO04',
    appId: '1:96137870116:web:9a53585e1fd0c42705d1b1',
    messagingSenderId: '96137870116',
    projectId: 'koopon-41d5a',
    authDomain: 'koopon-41d5a.firebaseapp.com',
    storageBucket: 'koopon-41d5a.firebasestorage.app',
    measurementId: 'G-WX3TL0G2ZC',
  );
}
